import type { Env } from "../env";
import { logError, logInfo } from "../logging";
import {
  assessMarketOpportunity,
  DEFAULT_OPPORTUNITY_THRESHOLDS,
  toOpportunityRows,
  type OpportunityDemand,
} from "../opportunity";
import type { ScoreRow } from "../scoring";
import {
  listObservationsForProducts,
  listProducts,
  upsertScores,
  type PersistedObservationRecord,
  type PersistedProductRecord,
} from "../supabase/repository";

/** Products loaded per page. Bounded so the whole catalog is never in memory. */
export const SCORING_BATCH_SIZE = 50;
/** Upper bound on products scored per run. */
export const SCORING_MAX_PRODUCTS = 200;

export type AutomatedScoringStatus = "ok" | "skipped" | "error";

/** Outcome of scoring one persisted product. */
export interface ScoreProductOutcome {
  rows: ScoreRow[];
  reason?: string;
}

/** Injection seam so tests can exercise per-product failure isolation. */
export type ScoreProductFn = (
  product: PersistedProductRecord,
  observation: PersistedObservationRecord | undefined,
) => ScoreProductOutcome;

export interface AutomatedScoringOptions {
  /** Page size; defaults to `SCORING_BATCH_SIZE`. */
  batchSize?: number;
  /** Maximum products to process; defaults to `SCORING_MAX_PRODUCTS`. */
  maxProducts?: number;
  /** Test seam; defaults to `scorePersistedProduct`. */
  scoreOne?: ScoreProductFn;
}

export interface AutomatedScoringSummary {
  status: AutomatedScoringStatus;
  total: number;
  scored: number;
  skipped: number;
  failed: number;
  persisted: number;
  durationMs: number;
  code?: string;
  message?: string;
  reasons?: Record<string, number>;
}

/**
 * Automated scoring pipeline (P7.30).
 *
 * Pages the most-recently-seen persisted products in bounded batches,
 * reconstructs the real demand inputs available for each product (observation
 * rating data), and persists `competition` / `market_opportunity` generated by
 * the existing P1.10 engine. `decision_opportunity` (P5.24) and the analyst
 * explanation (P5.25) stay on-read and are never written here.
 *
 * The discovery flow does not collect competitor data, so a competition score
 * has no signals to evaluate. That score is therefore skipped with an explicit
 * reason rather than persisting a fabricated zero; the market opportunity score
 * is persisted only when at least one signal (currently demand volume) is
 * present. One product failing never aborts the batch.
 */
export async function runAutomatedScoring(
  env: Env,
  options: AutomatedScoringOptions = {},
): Promise<AutomatedScoringSummary> {
  const startedAt = Date.now();
  const batchSize = Math.max(1, Math.floor(options.batchSize ?? SCORING_BATCH_SIZE));
  const maxProducts = Math.max(0, Math.floor(options.maxProducts ?? SCORING_MAX_PRODUCTS));
  const scoreOne = options.scoreOne ?? scorePersistedProduct;

  let total = 0;
  let scored = 0;
  let skipped = 0;
  let failed = 0;
  let persisted = 0;
  const reasons: Record<string, number> = {};
  const bump = (code: string): void => {
    reasons[code] = (reasons[code] ?? 0) + 1;
  };

  const finish = (
    status: AutomatedScoringStatus,
    extra: { code?: string; message?: string } = {},
  ): AutomatedScoringSummary => {
    const summary: AutomatedScoringSummary = {
      status,
      total,
      scored,
      skipped,
      failed,
      persisted,
      durationMs: Date.now() - startedAt,
      ...(Object.keys(reasons).length > 0 ? { reasons } : {}),
      ...extra,
    };
    const fields: Record<string, unknown> = {
      total: summary.total,
      scored: summary.scored,
      skipped: summary.skipped,
      failed: summary.failed,
      persisted: summary.persisted,
      durationMs: summary.durationMs,
    };
    if (summary.code) fields.code = summary.code;
    if (summary.message) fields.message = summary.message;
    if (summary.reasons) fields.reasons = summary.reasons;
    if (status === "ok") {
      logInfo("scheduled.scoring", fields);
    } else {
      logError("scheduled.scoring", fields);
    }
    return summary;
  };

  let offset = 0;
  while (offset < maxProducts) {
    const limit = Math.min(batchSize, maxProducts - offset);
    const page = await listProducts(env, { limit, offset });
    if (page.status === "credentials_missing") {
      return finish("skipped", { code: "SUPABASE_NOT_CONFIGURED", message: "Supabase is not configured" });
    }
    if (page.status === "error") {
      return finish("error", { code: page.code ?? "PRODUCT_LIST_FAILED", message: page.message });
    }
    if (page.status !== "found") {
      return finish("error", { code: "PRODUCT_LIST_FAILED", message: "Unexpected repository outcome" });
    }

    const products = page.data.products;
    if (products.length === 0) break;
    total += products.length;

    const observations = await listObservationsForProducts(
      env,
      products.map((product) => product.id),
    );
    if (observations.status === "credentials_missing") {
      return finish("skipped", { code: "SUPABASE_NOT_CONFIGURED", message: "Supabase is not configured" });
    }
    if (observations.status !== "found") {
      failed += products.length;
      bump("OBSERVATION_LIST_FAILED");
      offset += products.length;
      if (products.length < limit) break;
      continue;
    }

    const latest = latestObservationsByProduct(observations.data);
    const pending: ScoreRow[][] = [];
    for (const product of products) {
      try {
        const outcome = scoreOne(product, latest.get(product.id));
        if (outcome.rows.length === 0) {
          skipped += 1;
          bump(outcome.reason ?? "NO_SCORABLE_DATA");
        } else {
          pending.push(outcome.rows);
        }
      } catch {
        failed += 1;
        bump("SCORING_FAILED");
      }
    }

    if (pending.length > 0) {
      const rows = pending.flat();
      const write = await upsertScores(env, rows);
      if (write.status === "created" || write.status === "updated") {
        scored += pending.length;
        persisted += rows.length;
      } else if (write.status === "credentials_missing") {
        return finish("skipped", { code: "SUPABASE_NOT_CONFIGURED", message: "Supabase is not configured" });
      } else {
        failed += pending.length;
        bump(write.status === "invalid" ? "INVALID_SCORE_ROW" : "SCORES_UPSERT_FAILED");
      }
    }

    offset += products.length;
    if (products.length < limit) break;
  }

  return finish("ok");
}

/**
 * Scores one persisted product from real observation data. Competition has no
 * input in the discovery flow, so only `market_opportunity` is persisted today;
 * the competition row is emitted only if the engine actually evaluated a signal.
 */
export function scorePersistedProduct(
  product: PersistedProductRecord,
  observation: PersistedObservationRecord | undefined,
): ScoreProductOutcome {
  if (!observation) {
    return { rows: [], reason: "NO_OBSERVATION_DATA" };
  }

  const demand = demandFromObservation(observation);
  const result = assessMarketOpportunity(
    { competition: {}, demand },
    DEFAULT_OPPORTUNITY_THRESHOLDS,
  );
  const rows = toOpportunityRows(result, { productId: product.id });

  const selected: ScoreRow[] = [];
  if (result.competition.totalWeight > 0) selected.push(rows[0]);
  if (result.score.totalWeight > 0) selected.push(rows[1]);
  if (selected.length === 0) {
    const hasDemand = typeof demand.rating?.count === "number";
    return { rows: [], reason: hasDemand ? "NO_OPPORTUNITY_SIGNAL" : "NO_DEMAND_DATA" };
  }

  const computedAt = observation.last_seen_at;
  if (computedAt) {
    for (const row of selected) row.computed_at = computedAt;
  }
  return { rows: selected };
}

/** Mirrors `demandFromProduct` for the persisted observation shape. */
function demandFromObservation(observation: PersistedObservationRecord): OpportunityDemand {
  const demand: OpportunityDemand = {};
  const count = observation.rating_count;
  if (typeof count === "number" && Number.isFinite(count) && count > 0) {
    demand.rating = { count };
  }
  const average = observation.rating_average;
  if (typeof average === "number" && Number.isFinite(average)) {
    demand.rating = { ...(demand.rating ?? {}), average };
  }
  return demand;
}

function latestObservationsByProduct(
  rows: PersistedObservationRecord[],
): Map<string, PersistedObservationRecord> {
  const latest = new Map<string, PersistedObservationRecord>();
  for (const row of rows) {
    const existing = latest.get(row.product_id);
    if (!existing || compareIso(row.last_seen_at, existing.last_seen_at) > 0) {
      latest.set(row.product_id, row);
    }
  }
  return latest;
}

function compareIso(left: string, right: string): number {
  if (left === right) return 0;
  return left < right ? -1 : 1;
}
